name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GITALK_CLIENT_ID: ${{ secrets.GITALK_CLIENT_ID }}
      GITALK_CLIENT_SECRET: ${{ secrets.GITALK_CLIENT_SECRET }}
      GITALK_CLIENT_OWNER: ${{ secrets.GITALK_CLIENT_OWNER }}
      GITALK_CLIENT_REPO: ${{ secrets.GITALK_CLIENT_REPO }}
      GITALK_CLIENT_ADMIN: ${{ secrets.GITALK_CLIENT_ADMIN }}

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache Hugo resources
      - name: Cache Hugo resources
        uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/*.md') }}

      # Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      # Build the Hugo site
      - name: Build
        run: hugo --minify --gc --environment production

      # Cache updated Hugo resources
      - name: Save Cache
        uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/*.md') }}

      # Deploy the site to GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
          single-commit: true
