name: Deploy to Github Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache Hugo resources
      - name: Cache Hugo resources
        uses: actions/cache@v4
        with:
          path: resources
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/*.md') }}

      # Set up environment variables for Gitalk
      - name: Set up environment variables
        run: |
          export GITALK_CLIENT_ID=${{ secrets.GITALK_CLIENT_ID }}
          export GITALK_CLIENT_SECRET=${{ secrets.GITALK_CLIENT_SECRET }}
          export GITALK_CLIENT_OWNER=${{ secrets.GITALK_CLIENT_OWNER }}
          export GITALK_CLIENT_REPO=${{ secrets.GITALK_CLIENT_REPO }}
          export GITALK_CLIENT_ADMIN=${{ secrets.GITALK_CLIENT_ADMIN }}

      # Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      # Build the Hugo site
      - name: Build
        run: hugo --minify --gc

      # Deploy the site to GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
          single-commit: true
